let suggestions = [
    "Class 10 ",
    "Physic solution",
    "youtube.com",
    "YouTube",
    "YouTuber",
    "YouTube Channel",
    "Chemistry",
    "Bollywood",
    "Songs",
    "What is logarithm ?",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "WEB developement",
    "How to solve HOTS questions",
    "How to learn JavaScript",
    "How to become Freelancer",
    "How to become Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
    "Maths Solution for Class 11",
    "Device",
];
